services:
  frontend:
    image: nginx:latest
    container_name: board-frontend
    volumes:
      - ./dist/apps/frontend/browser:/usr/share/nginx/html
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf
    ports:
      - "4200:80"
    networks:
      - board-network

  backend:
    build:
      context: ./
      dockerfile: ./apps/backend/Dockerfile
    container_name: board-backend
    ports:
      - "3000"
    networks:
      - board-network

  reverse-proxy:
    image: nginx:latest
    container_name: board-reverse-proxy
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - board-network

  mongodb:
    image: mongo
    container_name: board-mongodb
    ports:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "supersecret"
      MONGO_INITDB_DATABASE: "boardapp"
    networks:
      - board-network

networks:
  board-network:
    driver: bridge