services:
  frontend:
    image: nginx:latest
    container_name: board-frontend
    volumes:
      - ./dist/apps/frontend/browser:/usr/share/nginx/html
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf
    networks:
      - board-network

  backend:
    container_name: board-backend
    image: node:latest
    volumes:
      - ./dist/apps/backend:/app/dist
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./node_modules:/app/node_modules
    working_dir: /app
    command: ["sh", "-c", "npm install && node /app/dist/"]
    networks:
      - board-network

  reverse-proxy:
    image: nginx:latest
    container_name: board-reverse-proxy
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - board-network

  mongodb:
    image: mongo
    container_name: board-mongodb
    ports:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "supersecret"
      MONGO_INITDB_DATABASE: "boardapp"
    networks:
      - board-network

  redis:
    image: redis:latest
    container_name: board-redis
    networks:
      - board-network

networks:
  board-network:
    driver: bridge